# Generated by Django 5.0.1 on 2024-02-09 15:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_remove_event_description'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Event',
            new_name='NewsAndEvent',
        ),
    ]
