# Generated by Django 5.0.1 on 2024-02-09 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_rename_event_newsandevent'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('cover_image', models.ImageField(upload_to='events/covers/')),
                ('description', models.TextField()),
                ('date', models.CharField(max_length=100)),
                ('registration_link', models.URLField()),
            ],
        ),
    ]
