# Generated by Django 5.0.1 on 2024-02-09 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_event_location_event_time_alter_event_cover_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='contact',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
