# Generated by Django 5.0.1 on 2024-02-09 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_event_contact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='time',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
