# Generated by Django 5.0.1 on 2024-02-09 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_testimonial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testimonial',
            name='comment',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='testimonial',
            name='name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='testimonial',
            name='position',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
