# Generated by Django 5.0.1 on 2024-02-11 06:35

import django_ckeditor_5.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_newsitem'),
    ]

    operations = [
        migrations.CreateModel(
            name='Director',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200, null=True)),
                ('image', models.ImageField(upload_to='director_image/')),
                ('position', models.CharField(blank=True, max_length=200, null=True)),
                ('about', django_ckeditor_5.fields.CKEditor5Field(blank=True, null=True)),
                ('biodata', models.FileField(upload_to='director/portfolio')),
                ('phone', models.CharField(blank=True, max_length=200, null=True)),
                ('address', models.CharField(blank=True, max_length=200, null=True)),
                ('email', models.EmailField(blank=True, max_length=200, null=True)),
                ('facebook', models.URLField(blank=True, null=True)),
                ('twitter', models.URLField(blank=True, null=True)),
                ('linkedin', models.URLField(blank=True, null=True)),
                ('google', models.URLField(blank=True, null=True)),
            ],
        ),
    ]
