# Generated by Django 5.0.1 on 2024-02-11 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_currentprogramme'),
    ]

    operations = [
        migrations.AlterField(
            model_name='currentprogramme',
            name='date',
            field=models.CharField(max_length=255),
        ),
    ]
