# Generated by Django 5.0.1 on 2024-02-11 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_alter_currentprogramme_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='currentprogramme',
            name='organisers',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='currentprogramme',
            name='date',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
