# Generated by Django 5.0.1 on 2024-02-11 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_currentprogramme_organisers_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='currentprogramme',
            name='time',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
