# Generated by Django 5.0.1 on 2024-02-11 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0020_nssunit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nssunit',
            name='college_department',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='nssunit',
            name='programme_officer',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='nssunit',
            name='secretary',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='nssunit',
            name='unit_no',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
