# Generated by Django 5.0.1 on 2024-02-11 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0021_alter_nssunit_college_department_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Counsellor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('qualification', models.CharField(blank=True, max_length=200, null=True)),
                ('contact_no', models.CharField(blank=True, max_length=15, null=True)),
                ('office_contact', models.CharField(blank=True, max_length=15, null=True)),
                ('consultation_time', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
