# Generated by Django 5.0.1 on 2024-02-11 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0022_counsellor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='counsellor',
            name='contact_no',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='counsellor',
            name='office_contact',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
