# Generated by Django 5.0.1 on 2024-02-11 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0024_annualreport'),
    ]

    operations = [
        migrations.CreateModel(
            name='GraceMarks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event', models.CharField(blank=True, max_length=255, null=True)),
                ('first', models.IntegerField(blank=True, default=0, null=True)),
                ('second', models.IntegerField(blank=True, default=0, null=True)),
                ('third', models.IntegerField(blank=True, default=0, null=True)),
                ('participation', models.IntegerField(blank=True, default=0, null=True)),
            ],
        ),
    ]
