# Generated by Django 5.0.1 on 2024-02-11 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0025_gracemarks'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gracemarks',
            name='first',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='gracemarks',
            name='participation',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='gracemarks',
            name='second',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='gracemarks',
            name='third',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
