# Generated by Django 5.0.1 on 2024-02-13 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0030_essentialinfo'),
    ]

    operations = [
        migrations.CreateModel(
            name='UniversityOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('order_pdf', models.FileField(upload_to='orders/')),
            ],
        ),
    ]
