# Generated by Django 5.0.1 on 2024-02-13 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0032_antiragging'),
    ]

    operations = [
        migrations.AlterField(
            model_name='antiragging',
            name='description',
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
    ]
