# Generated by Django 5.0.1 on 2024-02-13 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0033_alter_antiragging_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='antiragging',
            name='description',
            field=models.TextField(blank=True, max_length=2000, null=True),
        ),
    ]
