# Generated by Django 5.0.1 on 2024-02-13 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0034_alter_antiragging_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentAidFund',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True, max_length=2000, null=True)),
                ('order_pdf', models.FileField(upload_to='student-aid/')),
            ],
        ),
    ]
