# Generated by Django 5.0.1 on 2024-02-13 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0036_research'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nssunit',
            name='college_department',
        ),
        migrations.RemoveField(
            model_name='nssunit',
            name='programme_officer',
        ),
        migrations.RemoveField(
            model_name='nssunit',
            name='secretary',
        ),
        migrations.RemoveField(
            model_name='nssunit',
            name='unit_no',
        ),
        migrations.AddField(
            model_name='nssunit',
            name='coordinator_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='nssunit',
            name='phone_number',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
