# Generated by Django 5.0.1 on 2024-02-13 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0037_remove_nssunit_college_department_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Union',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('designation', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('address', models.CharField(blank=True, max_length=1500, null=True)),
                ('contact_number', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
