# Generated by Django 5.0.1 on 2024-02-13 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0039_healthcenter'),
    ]

    operations = [
        migrations.AddField(
            model_name='gracemarks',
            name='grace_mark_form',
            field=models.FileField(null=True, upload_to='grace_marks/'),
        ),
        migrations.AddField(
            model_name='gracemarks',
            name='uo_grace_mark_form',
            field=models.FileField(null=True, upload_to='grace_marks/'),
        ),
    ]
