# Generated by Django 5.0.1 on 2024-02-14 08:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0040_gracemarks_grace_mark_form_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='director',
            old_name='twitter',
            new_name='instagram',
        ),
    ]
