# Generated by Django 5.0.1 on 2024-02-14 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0042_doctor_nurse_delete_healthcenter'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentaidfund',
            name='awardees',
            field=models.FileField(blank=True, null=True, upload_to='student-aid/'),
        ),
    ]
