# Generated by Django 5.0.1 on 2024-02-16 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0047_courses_healthcentre_office_contact_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentaidfund',
            name='notification',
            field=models.FileField(blank=True, null=True, upload_to='student-aid/'),
        ),
    ]
