# Generated by Django 5.0.1 on 2024-02-16 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0050_radio'),
    ]

    operations = [
        migrations.AddField(
            model_name='radio',
            name='management_designation',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='radio',
            name='management_mobile_number',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='radio',
            name='management_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='radio',
            name='radio_jockey_address',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='radio',
            name='radio_jockey_contact_number',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='radio',
            name='radio_jockey_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
