# Generated by Django 5.0.1 on 2024-02-16 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0052_radio_link_to_radio_radio_link_to_youtube'),
    ]

    operations = [
        migrations.AddField(
            model_name='courses',
            name='duration_and_date',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='courses',
            name='registration_link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='courses',
            name='report',
            field=models.FileField(blank=True, null=True, upload_to='courses/'),
        ),
        migrations.AlterField(
            model_name='courses',
            name='details',
            field=models.FileField(blank=True, null=True, upload_to='courses/'),
        ),
    ]
