# Generated by Django 5.0.1 on 2024-02-16 18:19

import django_ckeditor_5.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0053_courses_duration_and_date_courses_registration_link_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='research',
            name='category',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='research',
            name='department_or_university',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='research',
            name='supervisor',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, null=True),
        ),
    ]
