# Generated by Django 5.0.1 on 2024-02-17 09:39

import django_ckeditor_5.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0054_research_category_research_department_or_university_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='radio_description_and_links',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', django_ckeditor_5.fields.CKEditor5Field(blank=True, null=True)),
                ('link_to_radio', models.URLField(blank=True, null=True)),
                ('link_to_youtube', models.URLField(blank=True, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='radio',
            name='description',
        ),
        migrations.RemoveField(
            model_name='radio',
            name='link_to_radio',
        ),
        migrations.RemoveField(
            model_name='radio',
            name='link_to_youtube',
        ),
        migrations.RemoveField(
            model_name='research',
            name='supervisor',
        ),
        migrations.AddField(
            model_name='research',
            name='research_supervisor',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='research',
            name='status',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
