# Generated by Django 5.0.1 on 2024-02-17 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0055_radio_description_and_links_remove_radio_description_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RadioJockey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('radio_jockey_name', models.CharField(blank=True, max_length=255, null=True)),
                ('radio_jockey_address', models.CharField(blank=True, max_length=500, null=True)),
                ('radio_jockey_contact_number', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='RadioManagement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('management_name', models.CharField(blank=True, max_length=255, null=True)),
                ('management_designation', models.CharField(blank=True, max_length=255, null=True)),
                ('management_mobile_number', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Radio',
        ),
    ]
