# Generated by Django 5.0.1 on 2024-02-17 10:06

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0056_radiojockey_radiomanagement_delete_radio'),
    ]

    operations = [
        migrations.AddField(
            model_name='research',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
