# Generated by Django 5.0.1 on 2024-02-17 10:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0057_research_created_at'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Alumni',
        ),
    ]
