# Generated by Django 5.0.1 on 2024-02-19 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0059_courses_created_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='testimonial',
            old_name='comment',
            new_name='testimonial',
        ),
        migrations.RemoveField(
            model_name='testimonial',
            name='image',
        ),
        migrations.AddField(
            model_name='testimonial',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='testimonials_photos/'),
        ),
        migrations.AlterField(
            model_name='testimonial',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='testimonial',
            name='position',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
