# Generated by Django 5.0.1 on 2024-02-19 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0060_rename_comment_testimonial_testimonial_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentaidfund',
            name='order_pdf',
            field=models.FileField(blank=True, null=True, upload_to='student-aid/'),
        ),
    ]
