# Generated by Django 5.0.1 on 2024-02-28 08:34

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0061_alter_studentaidfund_order_pdf'),
    ]

    operations = [
        migrations.AddField(
            model_name='universityorder',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
