# Generated by Django 5.0.1 on 2024-02-29 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0062_universityorder_created_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='SargamResults',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('individual_results', models.FileField(blank=True, null=True, upload_to='sargam_results/')),
                ('group_results', models.FileField(blank=True, null=True, upload_to='sargam_results/')),
            ],
        ),
    ]
