# Generated by Django 5.0.1 on 2024-07-26 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0063_sargamresults'),
    ]

    operations = [
        migrations.AddField(
            model_name='director',
            name='duties_and_responsibilities',
            field=models.FileField(blank=True, null=True, upload_to='director/portfolio'),
        ),
        migrations.AlterField(
            model_name='director',
            name='biodata',
            field=models.FileField(blank=True, null=True, upload_to='director/portfolio'),
        ),
    ]
